import React from "react";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { SecurityAlertsPanel, SecurityAlertItem } from "@/components/dashboard/security-alerts-panel";
import { DataTableSearch } from "@/components/dashboard/data-table-search";
import { DataTablePagination } from "@/components/dashboard/data-table-pagination";
import { Card, CardContent } from "@/components/ui/card";
import { ShieldAlert } from "lucide-react";

export const dynamic = "force-dynamic";

interface AlertsPageProps {
  searchParams: Promise<{
    page?: string;
    search?: string;
    severity?: string;
    resolved?: string;
  }>;
}

export default async function AlertsPage({ searchParams }: AlertsPageProps) {
  const params = await searchParams;
  const rawPage = parseInt(params.page || "1", 10);
  const page = Math.max(1, isNaN(rawPage) ? 1 : rawPage);
  const limit = 20;
  const search = (params.search || "").trim();
  const severityFilter = (params.severity || "").trim().toLowerCase();
  const resolvedFilter = params.resolved === undefined ? "false" : params.resolved;

  const where: any = {};

  if (severityFilter && ["low", "medium", "high", "critical"].includes(severityFilter)) {
    where.severity = severityFilter;
  }

  if (resolvedFilter === "false") {
    where.resolved = false;
  } else if (resolvedFilter === "true") {
    where.resolved = true;
  }

  if (search) {
    const terms = search.split(/\s+/).filter(Boolean);
    if (terms.length > 0) {
      where.AND = terms.map((term) => ({
        OR: [
          { title: { contains: term, mode: "insensitive" } },
          { message: { contains: term, mode: "insensitive" } },
        ],
      }));
    }
  }

  const total = await prisma.alert.count({ where });
  const totalPages = Math.ceil(total / limit) || 1;
  const skip = (page - 1) * limit;

  const rawAlerts = await prisma.alert.findMany({
    where,
    skip,
    take: limit,
    orderBy: { createdAt: "desc" },
    include: {
      person: {
        select: {
          id: true,
          personCode: true,
          firstName: true,
          lastName: true,
        },
      },
    },
  });

  const alerts: SecurityAlertItem[] = rawAlerts.map((alt) => ({
    id: alt.id,
    alertType: alt.alertType,
    title: alt.title,
    message: alt.message,
    severity: alt.severity as any,
    resolved: alt.resolved,
    createdAt: alt.createdAt.toISOString(),
    person: alt.person,
  }));

  return (
    <div className="p-4 sm:p-6 md:p-10 max-w-7xl mx-auto space-y-4 sm:space-y-6 bg-background text-foreground">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border pb-6">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-2 bg-amber-500/10 border border-amber-500/20 text-amber-500 rounded-lg shrink-0">
              <ShieldAlert className="w-5 h-5" />
            </span>
            <h1 className="text-2xl font-bold text-foreground tracking-tight">Security Alerts Center</h1>
          </div>
          <p className="text-sm text-muted-foreground">
            Monitor and resolve security anomaly alerts generated by the access control engine.
          </p>
        </div>
      </div>

      {/* Standardized Search & Filter Header Bar */}
      <Card className="border border-border shadow-sm">
        <CardContent className="p-4 flex flex-col md:flex-row items-center justify-between gap-4">
          <DataTableSearch
            placeholder="Search alerts by title or message..."
            className="max-w-none flex-1"
          />

          <div className="flex flex-wrap items-center gap-2 w-full md:w-auto">
            {/* Resolution Filter Pills */}
            <Link
              href={`/dashboard/alerts?page=1&search=${encodeURIComponent(search)}&severity=${severityFilter}&resolved=false`}
              className={`text-xs px-3 py-1.5 rounded-lg border font-medium transition-all ${
                resolvedFilter === "false" ? "bg-amber-500/10 text-amber-500 border-amber-500/30 font-semibold" : "bg-background border-input text-muted-foreground hover:text-foreground"
              }`}
            >
              Unresolved
            </Link>
            <Link
              href={`/dashboard/alerts?page=1&search=${encodeURIComponent(search)}&severity=${severityFilter}&resolved=true`}
              className={`text-xs px-3 py-1.5 rounded-lg border font-medium transition-all ${
                resolvedFilter === "true" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30 font-semibold" : "bg-background border-input text-muted-foreground hover:text-foreground"
              }`}
            >
              Resolved
            </Link>
            <Link
              href={`/dashboard/alerts?page=1&search=${encodeURIComponent(search)}&severity=${severityFilter}&resolved=`}
              className={`text-xs px-3 py-1.5 rounded-lg border font-medium transition-all ${
                resolvedFilter === "" ? "bg-primary text-primary-foreground border-primary font-semibold" : "bg-background border-input text-muted-foreground hover:text-foreground"
              }`}
            >
              All Alerts
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* Alerts Panel & Pagination Container */}
      <Card className="border border-border shadow-sm overflow-hidden space-y-0">
        <CardContent className="p-4 sm:p-6">
          <SecurityAlertsPanel alerts={alerts} />
        </CardContent>

        <DataTablePagination
          total={total}
          page={page}
          limit={limit}
          totalPages={totalPages}
          itemLabel="alerts"
        />
      </Card>
    </div>
  );
}
